name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101   
    - name: Install dependencies
      run: dotnet restore
    - name: Build netcoreapp3.1
      run: dotnet build --configuration Release --no-restore --framework netcoreapp3.1
    - name: Test netcoreapp3.1
      run: dotnet run -c Release  --framework netcoreapp3.1
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.6.20318.15
    - name: Install dependencies
      run: dotnet restore
    - name: Build net5.0
      run: dotnet build --configuration Release --no-restore --framework net5.0
    - name: Test net5.0
      run: dotnet run -c Release  --framework net5.0
